### ISSUE TITLE
[Feature Request] Start Hour and End Hour

### ISSUE THREAD

**Issue by benyaminl** [ArcaEge/day-progress#1]
If possible, could you please add a settings feature for setting work time and the end worktime, so it would be cool to see clock like that at your bar. 

Thank you

**Comment by Wyesumu** [comment]
Made pull request for that change: https://github.com/ArcaEge/day-progress/pull/3

**Comment by ArcaEge** [comment]
Hello, it's mostly done thanks to @Wyesumu but it is missing wrapping around midnight, if you do not need the feature, you can install the extension as-is from the main branch now. I'm working on the fix for it and it should be out in a day or two hopefully.

**Comment by ArcaEge** [comment]
I've pushed the fix, it may take a day or so to get the new update approved but it's done
![image](https://github.com/ArcaEge/day-progress/assets/40526225/71c9fd39-b6b4-4a6f-bd22-05f3d847a252)
