### ISSUE TITLE
Almost invisible with Adwaita light theme

### ISSUE THREAD

**Issue by mapuo** [ArcaEge/day-progress#10]
Hi,

I'm using [Night Theme Switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) to change between Adwaita dark and light themes, but you can do that with a command as well (ex.: `gsettings set org.gnome.desktop.interface color-scheme prefer-light`).

My issue is when the light theme is selected the day-progress is not visible, like in this screenshot:

![image](https://github.com/ArcaEge/day-progress/assets/99132/1b1b91d5-e775-441b-b80c-5c17b902cd68)

**Comment by ArcaEge** [comment]
OK, I'll be having a look at this soon. Do other extensions have this issue? Also, are you using a custom shell theme? The top panel is dark with the default theme even when light mode is enabled.

**Comment by ArcaEge** [comment]
There's no way to make this work with CSS only to my knowledge, therefore if what you are using is a theme, it won't work. However, if it is GNOME classic, I can add a check to use a second CSS file if GNOME classic is being used

**Comment by ArcaEge** [comment]
I've added GNOME classic support in commit [d398a9d](https://github.com/ArcaEge/day-progress/commit/d398a9d2e5eefb6d951e58617fcf9a430ff348f1)

**Comment by mapuo** [comment]
Well, that was fast. :)
I'm using Arch with Gnome, I guess it is 'classic' - I don't have additional themes installed, but I'm not sure. If there is a way to check, please, tell me and I'll check it.
Extension Manager shows the Day Progress at version 11:
![image](https://github.com/ArcaEge/day-progress/assets/99132/26162a48-6ff1-4ff3-a4ea-d2a644c166a9)
Is this the version with these changes or should I wait for the next version?

**Comment by ArcaEge** [comment]
Yes, v11 should be the one with the changes, although if you are using Wayland (`echo $XDG_SESSION_TYPE`) you need to log out for the update to apply. If you are on X11, you can press Alt+F2 and type in 'r' instead of logging out. You should be able to check if you're using classic checking the value of `GNOME_SHELL_SESSION_MODE` by:
``` bash
echo $GNOME_SHELL_SESSION_MODE
```
If you're using classic, it should print 'classic', although if you're on plain GNOME it won't print anything. If you want to switch between the two, (I'm guessing you have GDM installed since you're using GNOME) you can log out and click on the cog in the bottom right when logging in.

If I sound verbose (I realise you're using arch) it's so that ubuntu users can understand :)

**Comment by mapuo** [comment]
Oh, OK. So it seems that I'm on just GNOME, without the 'classic' - when I go the the login screen cogwheel it says so. According to Arch Wiki it is the default Gnome running on Wayland. When I run the `echo $GNOME_SHELL_SESSION_MODE` it prints empty line.
But the change does not work in that mode - it is still light on the light theme.
Is this something related with Wayland or is it something else?

**Comment by ArcaEge** [comment]
That's strange... do you have the 'user themes' extension installed? Also, are there any panel-related extansions installed? I should probably re-open the issue in that case.

**Comment by mapuo** [comment]
User Themes is installed and enabled.
I see also [Light Style](https://extensions.gnome.org/extension/6198/light-style/) is installed and enabled.
I may have some extension that does something to the Panel, but I'm not sure - I'll test.
And yes, the Panel colour changes from light to dark and back again when I enable/disable Dark mode.

**Comment by ArcaEge** [comment]
> I may have some extension that does something to the Panel, but I'm not sure - I'll test.

Yes, the Light Style extension seems to do just that. Thankfully, it's a mostly simple fix - it just seems to update `sessionMode.colorScheme` from `resource:///org/gnome/shell/ui/main.js`. I'll be working on it now.

**Comment by ArcaEge** [comment]
OK, so I've done it :tada:
![image](https://github.com/ArcaEge/day-progress/assets/40526225/aa7b95ae-d6d3-4685-879d-026655a607f1)

However, it only works when Light Style and light mode are used together. When you enable dark mode with Light Style (the extension) enabled, the panel will be dark but so will the extension. I'm working on a fix for that now.

**Comment by ArcaEge** [comment]
It's done, uploading to Extensions.

**Comment by ArcaEge** [comment]
I'm closing the issue now.
