### ISSUE TITLE
Color scheme in Ubuntu

### ISSUE THREAD

**Issue by alk3mist** [ArcaEge/day-progress#13]
Hello, I use Ubuntu 24.04 / Gnome 46.
By default, the top bar in Ubuntu is always black. And the day-progress bar is barely visible.

The configuration parameter `org.gnome.desktop.interface.color-scheme` in Ubuntu is the enumeration:
 `'default', 'prefer-light', 'prefer-dark'`. 
When I select either the 'prefer-light' or 'prefer-dark' option, then the day-progress bar is white. 
But when the 'default' option is set, then the bar is barely visible(`rgba(40, 40, 40, 1)` I guess).

**Comment by alk3mist** [comment]
I tried with and without the Light Style enabled. The behaviour has not changed.

**Comment by ArcaEge** [comment]
I can't reproduce the issue on Fedora 40 which is what I'm using; it's probably related to the Ubuntu customisations. I'm having a look now in the VM. Can you tell me whether you're using X11 or Wayland?

**Comment by alk3mist** [comment]
I use Wayland

**Comment by ArcaEge** [comment]
![image](https://github.com/user-attachments/assets/ac7637de-ca9c-40bb-bd78-a64196bc0574)
Alright, I can reproduce this. I'm having a look

**Comment by ArcaEge** [comment]
I've fixed it now, but it breaks compatibility with the Light Style extension. I'm trying to get both of them to work now.

**Comment by ArcaEge** [comment]
The Light Style extension uses a weird way of setting the theme so I'm going to ignore it for now.

**Comment by ArcaEge** [comment]
I'm now sending the extension off to be reviewed. Once you get the update and check it worked, can you please update your review at https://extensions.gnome.org/extension/7042/day-progress/ to reflect the changes? (I'm assuming it was your review based on timing and when it was posted, sorry if I'm wrong)

**Comment by alk3mist** [comment]
Thank you, @ArcaEge. I can confirm that the bar is well visible now on Ubuntu 24.04. 
I tried different values for the color-scheme options:
With 'default' I get white, with 'prefer-light' - black and with 'prefer-dark' - white again. I think this is what Ubuntu users expect.

This isn't my review, I went straight to Github)
