### ISSUE TITLE
[Feature Request] Extension panel position 

### ISSUE THREAD

**Issue by chikobara** [ArcaEge/day-progress#2]
Maybe adding a position control  for the extension would be cool, (Left, Right, Mid, and index to reorder its pos at the same side )

**Comment by ArcaEge** [comment]
Good idea, it's on my todo list now but I won't be able to work on it much for a few weeks as I'll be busy so if you can create a pull request (if you are able to) then it would be great!

**Comment by ArcaEge** [comment]
Hello, it's implemented now and I've uploaded it to GNOME extensions. It should get approved by tomorrow but until then you can install it from the repo.
